apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bills-update-logs
  namespace: bills-update
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi 