import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// Builds lib/og/fonts.ts: the three brand faces (Documentation/brand.md,
// "Type") as base64, for the per-bill share image drawn by
// app/bills/[id]/share-image/route.tsx.
//
// Why embedded rather than read at request time: the image renders inside a
// Cloudflare Worker, which has no filesystem to read a .ttf from, and fetching
// the font from Google on every render would put a third party in the path of
// every link preview. Why TTF: the renderer (satori, via next/og) reads TTF,
// OTF and WOFF but not WOFF2, which is all next/font keeps.
//
// Run manually and commit the result — it is NOT part of the build:
//
//   pip install fonttools
//   pnpm exec tsx scripts/generate-og-fonts.ts
//
// The subset keeps Latin-1 plus the punctuation bill titles actually use
// (curly quotes, dashes, the ellipsis, the middle dot), which brings the four
// files from ~360 KB to ~130 KB. A character outside it falls back to next/og's
// bundled Geist Regular. All three faces are under the SIL Open Font License.

const FACES = [
  // Newsreader's display cut (opsz 72) — the one headlines use on the site.
  { name: 'newsreader500', family: 'Newsreader:opsz,wght@72,500' },
  { name: 'newsreader600', family: 'Newsreader:opsz,wght@72,600' },
  { name: 'geist500', family: 'Geist:wght@500' },
  { name: 'geistMono500', family: 'Geist+Mono:wght@500' },
] as const;

const UNICODES = [
  'U+0020-007E', // Basic Latin
  'U+00A0-00FF', // Latin-1 (accented names, §, ·, ©)
  'U+0131,U+0152-0153,U+02C6,U+02DA,U+02DC',
  'U+2013-2014', // en and em dash
  'U+2018-201A,U+201C-201E', // curly quotes
  'U+2022,U+2026', // bullet, ellipsis
  'U+2032-2033,U+2039-203A,U+20AC,U+2122',
].join(',');

// An old user agent makes Google Fonts answer with TTF instead of WOFF2.
const LEGACY_UA = 'Mozilla/4.0';

const output = join(process.cwd(), 'lib', 'og', 'fonts.ts');

async function ttfUrl(family: string): Promise<string> {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${family}`, {
    headers: { 'user-agent': LEGACY_UA },
  });
  if (!res.ok) throw new Error(`Google Fonts CSS for ${family}: HTTP ${res.status}`);
  const css = await res.text();
  const match = css.match(/url\((https:[^)]+\.ttf)\)/);
  if (!match) throw new Error(`No TTF source for ${family} in:\n${css}`);
  return match[1];
}

async function main() {
  const dir = await mkdtemp(join(tmpdir(), 'og-fonts-'));
  try {
    const lines: string[] = [];
    for (const face of FACES) {
      const url = await ttfUrl(face.family);
      const raw = join(dir, `${face.name}.ttf`);
      const sub = join(dir, `${face.name}.sub.ttf`);
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
      await writeFile(raw, Buffer.from(await res.arrayBuffer()));
      execFileSync('pyftsubset', [
        raw,
        `--unicodes=${UNICODES}`,
        '--layout-features=kern,liga,lnum,tnum',
        `--output-file=${sub}`,
      ]);
      const data = await readFile(sub);
      console.log(`${face.name}: ${data.length} bytes`);
      lines.push(`export const ${face.name} = '${data.toString('base64')}';`);
    }

    await writeFile(
      output,
      [
        '// GENERATED by scripts/generate-og-fonts.ts — do not edit by hand.',
        '//',
        '// Newsreader, Geist and Geist Mono (SIL Open Font License 1.1), subset to',
        '// Latin-1 and common punctuation, as base64 TTF for the share image.',
        '/* eslint-disable */',
        '',
        ...lines,
        '',
      ].join('\n'),
    );
    console.log(`Wrote ${output}`);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error('OG font generation failed:', error);
  process.exit(1);
});
